USE [DevelopmentDashboard]
GO

/****** Object:  Table [dbo].[PublicAccessRules]    Script Date: 26.05.2016 1:35:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PublicAccessRules](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Mask] [varchar](150) NULL,
 CONSTRAINT [PK_PublicAccessRules] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


